-- Módulo 1: Seguridad y Administración

CREATE TABLE public.Roles (
  id_rol bigint generated by default as identity primary key,
  nombre_rol text not null,
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

CREATE TABLE public.Empleados (
  id uuid primary key references auth.users(id) on delete cascade,
  id_rol bigint references public.Roles(id_rol),
  nombre text not null,
  apellido text not null,
  nombre_usuario text not null unique,
  correo text unique,
  esta_activo boolean default true,
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

-- Módulo 2: Configuración de Productos y Categorías

CREATE TABLE public.Categorias_Productos (
  id_categoria bigint generated by default as identity primary key,
  nombre_categoria text not null,
  created_at timestamp with time zone default now(),
  created_by uuid
);

CREATE TABLE public.Productos (
  id_producto bigint generated by default as identity primary key,
  id_categoria bigint references public.Categorias_Productos(id_categoria),
  nombre_producto text not null,
  precio_unitario decimal(10,2) not null,
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

-- Módulo 3: Clientes y Convenios Unificados

CREATE TABLE public.Tipos_Cliente (
  id_tipo_cliente bigint generated by default as identity primary key,
  nombre_tipo text not null -- Ej. 'Frecuente/Prepago', 'Convenio/Empresa'
);

CREATE TABLE public.Convenios (
  id_convenio uuid default gen_random_uuid() primary key,
  ruc text not null unique,
  nombre_empresa text not null,
  representante text,
  telefono text,
  email text,
  fecha_inicio date not null,
  fecha_caducidad date not null,
  esta_activo boolean default true,
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

CREATE TABLE public.Clientes (
  id_cliente uuid default gen_random_uuid() primary key,
  id_tipo_cliente bigint references public.Tipos_Cliente(id_tipo_cliente),
  cedula text unique not null,
  nombre text not null,
  apellido text not null,
  telefono text,
  esta_activo boolean default true,
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

-- Relación para saber a qué empresa pertenece un cliente de convenio
CREATE TABLE public.Clientes_Convenios (
  id_cliente uuid references public.Clientes(id_cliente) on delete cascade,
  id_convenio uuid references public.Convenios(id_convenio) on delete cascade,
  created_at timestamp with time zone default now(),
  created_by uuid,
  primary key (id_cliente, id_convenio)
);

-- Módulo 4: Monedero Virtual (Para Clientes Frecuentes)

CREATE TABLE public.Saldos_Servicio (
  id_cliente uuid references public.Clientes(id_cliente) on delete cascade,
  id_producto bigint references public.Productos(id_producto) on delete cascade,
  cantidad_disponible int not null default 0,
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid,
  primary key (id_cliente, id_producto)
);

CREATE TABLE public.Recargas_Saldo (
  id_recarga uuid default gen_random_uuid() primary key,
  id_cliente uuid references public.Clientes(id_cliente) on delete cascade,
  id_producto bigint references public.Productos(id_producto),
  cantidad_comprada int not null,
  monto_total decimal(10,2) not null,
  numero_factura varchar(50),             -- N° de factura entregado en caja (trazabilidad)
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

-- Módulo 5: Operación y Ventas (Gestión de Consumos)

CREATE TABLE public.Estados_Orden (
  id_estado bigint generated by default as identity primary key,
  nombre_estado text not null -- Ej. Reservado, Completado, Cancelado
);

CREATE TABLE public.Origenes_Pedido (
  id_origen bigint generated by default as identity primary key,
  nombre_origen text not null -- Ej. Bot de Mensajería, Dashboard Manual
);

CREATE TABLE public.Ordenes (
  id_orden uuid default gen_random_uuid() primary key,
  id_cliente uuid references public.Clientes(id_cliente),
  id_estado bigint references public.Estados_Orden(id_estado),
  id_origen bigint references public.Origenes_Pedido(id_origen),
  id_empleado_atiende uuid references public.Empleados(id), -- El humano que despacha
  canal_origen text, 
  metodo_pago text, -- Ej. 'Saldo Prepago', 'Convenio Empresa', 'Efectivo'
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

CREATE TABLE public.Detalle_Orden (
  id_detalle uuid default gen_random_uuid() primary key,
  id_orden uuid references public.Ordenes(id_orden) on delete cascade,
  id_producto bigint references public.Productos(id_producto),
  cantidad int not null,
  precio_aplicado decimal(10,2) not null, -- Precio pactado al momento de la orden
  opciones jsonb default '{}'::jsonb, -- Opciones elegidas (sopa, segundo, guarnicion, etc)
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

-- Función y Triggers para actualización automática de updated_at

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_roles_updated_at BEFORE UPDATE ON public.Roles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_empleados_updated_at BEFORE UPDATE ON public.Empleados FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_productos_updated_at BEFORE UPDATE ON public.Productos FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_convenios_updated_at BEFORE UPDATE ON public.Convenios FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_clientes_updated_at BEFORE UPDATE ON public.Clientes FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_saldos_updated_at BEFORE UPDATE ON public.Saldos_Servicio FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_ordenes_updated_at BEFORE UPDATE ON public.Ordenes FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_detalle_orden_updated_at BEFORE UPDATE ON public.Detalle_Orden FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Módulo 6: Gestión de Menú Diario (Catálogo de Alimentos)

CREATE TABLE public.Categorias_Menu (
  id_categoria_menu bigint generated by default as identity primary key,
  nombre_categoria text not null, -- Ej: 'Sopa', 'Segundo', 'Guarnición'
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

CREATE TABLE public.Alimentos (
  id_alimento bigint generated by default as identity primary key,
  id_categoria_menu bigint references public.Categorias_Menu(id_categoria_menu) on delete cascade,
  nombre_alimento text not null, -- Ej: 'Sopa de Arroz', 'Pollo al Horno'
  created_at timestamp with time zone default now(),
  created_by uuid,
  updated_at timestamp with time zone default now(),
  updated_by uuid
);

CREATE TRIGGER update_categorias_menu_updated_at BEFORE UPDATE ON public.Categorias_Menu FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_alimentos_updated_at BEFORE UPDATE ON public.Alimentos FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Módulo 7: Menú Diario (Configuración por Fecha)

CREATE TABLE public.Menu_Diario (
  id_menu_diario uuid default gen_random_uuid() primary key,
  fecha date not null,
  id_alimento bigint references public.Alimentos(id_alimento) on delete cascade,
  created_at timestamp with time zone default now(),
  created_by uuid,
  unique(fecha, id_alimento)
);
